name: Build

on:
  push:
    tags:
    - 'latest'
    - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CI: true
  # don't print dotnet logo
  DOTNET_NOLOGO: true
  # disable telemetry (reduces dotnet tool output in logs)
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-dotnet:
    name: Build Dotnet
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
      
      - name: Build
        run: dotnet build --configuration release

      - name: Pack
        run: dotnet pack --configuration release

      - name: Upload Nuget packages
        uses: actions/upload-artifact@v4
        with:
          name: bicep-types-packages
          path: ./out/*
          if-no-files-found: error

      - name: Test
        run: dotnet test --configuration release --collect:"XPlat Code Coverage" --settings ./.github/workflows/codecov.runsettings

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v5
        with:
          flags: dotnet

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build-npm:
    name: Build NPM
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      
      - name: Install
        run: npm ci
        working-directory: ./src/bicep-types
      
      - name: Lint
        run: npm run lint
        working-directory: ./src/bicep-types
      
      - name: Test
        run: npm test
        working-directory: ./src/bicep-types
      
      - name: Build
        run: npm run build
        working-directory: ./src/bicep-types

      - name: Package
        run: |
          npm run package
          mv bicep-types-*.tgz bicep-types.tgz
        working-directory: ./src/bicep-types

      - name: Upload NPM package
        uses: actions/upload-artifact@v4
        with:
          name: bicep-types.tgz
          path: ./src/bicep-types/bicep-types.tgz
          if-no-files-found: error

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: ./src/bicep-types-go/go.sum

      - name: Verify dependencies
        run: go mod verify
        working-directory: ./src/bicep-types-go

      - name: Download dependencies
        run: go mod download
        working-directory: ./src/bicep-types-go

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        run: golangci-lint run
        working-directory: ./src/bicep-types-go

      - name: Build
        run: go build -v ./...
        working-directory: ./src/bicep-types-go

      - name: Test (Unit)
        run: go test -v -race -coverprofile=coverage.out ./...
        working-directory: ./src/bicep-types-go

      - name: Build CLI binary
        run: |
          go build -o bicep-types ./cmd/bicep-types
          chmod +x bicep-types
        working-directory: ./src/bicep-types-go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3